"""
Django settings for PROJECTO project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from celery.schedules import crontab
import firebase_admin
from decouple import config
from firebase_admin import credentials
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f620y=yye-7&=olprx1yjonx&bi_xjj+w+1j(r*-glwr-v+4u2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    #'microcredito_app',
    'microcredito_app.apps.MicrocreditoAppConfig',
    'fcm_django',
    'rest_framework',
    
    
]

CRISPY_ALLOWED_TEMPLATE = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'microcredito_app.middleware.PermissaoMiddleware',
]

ROOT_URLCONF = 'PROJECTO.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'microcredito_app/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'microcredito_app.context_processors.notificacoes'
            ],
        },
    },
]

WSGI_APPLICATION = 'PROJECTO.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'microcredito_db',
        'USER': 'postgres',
        'PASSWORD': 'admin123',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR / 'static')
]  # Aponta para a pasta static na raiz
#STATIC_ROOT = BASE_DIR / 'staticfiles'     # Para produção

# Configurações de autenticação
LOGIN_URL = 'login'           # URL para redirecionar usuários não autenticados
LOGIN_REDIRECT_URL = 'dashboard'  # URL após login bem-sucedido
LOGOUT_REDIRECT_URL = 'inicio'    # URL após logout

# Para usar e-mail como identificador principal
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
# Firebase Configuration
FIREBASE_CONFIG = {
    'apiKey': "AIzaSyCmRtDskJ4qkIA3RNmDKwR8XvsazHBic2w",
    'authDomain': "codemindmicrocredito-app.firebaseapp.com",
    'projectId': "codemindmicrocredito-app",
    'storageBucket': "codemindmicrocredito-app.firebasestorage.app",
    'messagingSenderId': "319943045295",
    'appId': "1:319943045295:web:3da299b2c07580ff82645a",
    'measurementId': "G-VC4H0PKTXK"
}
FIREBASE_CREDENTIALS_PATH = os.path.join(BASE_DIR, 'firebase-service-account.json')

if os.path.exists(FIREBASE_CREDENTIALS_PATH):
    cred = credentials.Certificate(FIREBASE_CREDENTIALS_PATH)
    firebase_admin.initialize_app(cred)
# ============================================
# CHAVES VAPID PARA PUSH NOTIFICATIONS
# ============================================
VAPID_PUBLIC_KEY = 'BFyUoVAuVBAhl8Gi0UR6w8GMGd0W3UdFponSNsVHdn9IL85f63WAuPnqyqsjLEqVA_wMYuBe6QuYup2ULiS_2Hc'
VAPID_PRIVATE_KEY = 'jfPJJ79Rts5syf4PS2Wr_KSfaBKsxDK1oI9Ja0I1kVY'
VAPID_EMAIL = 'apoiocodeminde@gmail.com'

# ============================================
# CONFIGURAÇÕES DO CELERY
# ============================================

CELERY_BROKER_URL = 'redis://localhost:6380/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6380/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE



CELERY_BEAT_SCHEDULE = {
    'enviar-notificacoes-a-cada-hora': {
        'task': 'microcredito_app.tasks.enviar_notificacoes_automaticas',
        'schedule': crontab(minute=0, hour='*/1'),  # A cada 1 hora
    },
}
# firebase_admin
FCM_DJANGO_SETTINGS = {
    "ONE_DEVICE_PER_USER": True,
    "DELETE_INACTIVE_DEVICES": True,
}

# ============================================
# CONFIGURAÇÕES DE EMAIL PARA RECUPERAÇÃO DE SENHA
# ============================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Para Gmail
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'apoiocodeminde@gmail.com'  # Substitua pelo seu email
EMAIL_HOST_PASSWORD = '2Joelabrao'   # Substitua pela senha de app
DEFAULT_FROM_EMAIL = 'CODE-MIND <apoiocodeminde@gmail.com>'

# PaySuite Configuration
PAYSUITE_CONFIG = {
    'API_BASE_URL': 'https://paysuite.tech/api/v1',
    'API_TOKEN': 'your_api_token_here',  # Obtenha do painel do comerciante
    'WEBHOOK_SECRET': 'your_webhook_secret',  # Configure no painel
    'DEFAULT_METHOD': 'emola',
    'TIMEOUT': 30,  # segundos
    'MAX_RETRIES': 3,
}
# PaySuite Configuration
PAYSUITE_API_KEY = os.getenv('PAYSUITE_API_KEY')
PAYSUITE_WEBHOOK_SECRET = os.getenv('PAYSUITE_WEBHOOK_SECRET')
PAYSUITE_ACCOUNT_ID = os.getenv('PAYSUITE_ACCOUNT_ID', default='')
PAYSUITE_ENVIRONMENT = os.getenv('PAYSUITE_ENVIRONMENT', default='sandbox')
PAYSUITE_CALLBACK_URL = os.getenv('PAYSUITE_CALLBACK_URL', default='')


# URLs para redirecionamento
PAYSUITE_RETURN_URL = 'https://3a6e-197-218-106-190.ngrok-free.app/payment/callback'
PAYSUITE_CALLBACK_URL = 'https://3a6e-197-218-106-190.ngrok-free.app/api/webhooks/paysuite'

# ============================================
# CONFIGURAÇÕES DE EMAIL PARA DESENVOLVIMENTO
# ============================================
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# Isso faz os emails aparecerem no terminal, não enviados de verdade
#7IstoeIts@apoiocustomer#