# Generated by Django 6.0.2 on 2026-03-24 08:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(help_text='Exemplo: 841234567 ou 851234567', max_length=15, verbose_name='Telefone/WhatsApp')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('renda_mensal', models.DecimalField(blank=True, decimal_places=2, help_text='Usado para análise de crédito', max_digits=12, null=True, verbose_name='Renda Mensal (MT)')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-data_cadastro'],
                'unique_together': {('usuario', 'telefone')},
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor mínimo: 100 MT', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('100.00'))], verbose_name='Valor do Empréstimo (MT)')),
                ('taxa_juros', models.DecimalField(decimal_places=2, help_text='Exemplo: 5.00 = 5%', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taxa de Juros (%)')),
                ('quantidade_parcelas', models.IntegerField(help_text='Máximo 60 parcelas', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Parcelas')),
                ('tipo_juros', models.CharField(choices=[('simples', 'Juros Simples'), ('composto', 'Juros Compostos')], default='composto', max_length=10, verbose_name='Tipo de Juros')),
                ('valor_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor da Parcela (MT)')),
                ('data_contrato', models.DateField(auto_now_add=True, verbose_name='Data do Contrato')),
                ('data_primeiro_vencimento', models.DateField(verbose_name='Data do Primeiro Vencimento')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='ativo', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='microcredito_app.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número da Parcela')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (MT)')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado')], default='pendente', max_length=20, verbose_name='Status')),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='microcredito_app.emprestimo', verbose_name='Empréstimo')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Pago (MT)')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('transferencia', 'Transferência Bancária'), ('cartao', 'Cartão de Débito/Crédito'), ('deposito', 'Depósito Bancário'), ('outros', 'Outros')], max_length=20, verbose_name='Forma de Pagamento')),
                ('data_pagamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pagamento')),
                ('comprovante', models.FileField(blank=True, help_text='JPG, PNG ou PDF (max 5MB)', null=True, upload_to='comprovantes/%Y/%m/', verbose_name='Comprovante')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('parcela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='microcredito_app.parcela', verbose_name='Parcela')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, help_text='Formato: 84 1234567 ou 841234567', max_length=20, null=True, verbose_name='Telefone/WhatsApp')),
                ('notificacao_whatsapp', models.BooleanField(default=True, verbose_name='Receber notificações via WhatsApp')),
                ('notificacao_sms', models.BooleanField(default=True, verbose_name='Receber notificações via SMS')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Usuário',
                'verbose_name_plural': 'Perfis dos Usuários',
            },
        ),
    ]
