# Generated by Django 6.0.2 on 2026-03-30 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcredito_app', '0002_plano_alter_perfilusuario_telefone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoMPESA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (MT)')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone M-PESA')),
                ('referencia', models.CharField(max_length=50, unique=True, verbose_name='Referência')),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Checkout Request ID')),
                ('merchant_request_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Merchant Request ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('sucesso', 'Sucesso'), ('falhou', 'Falhou'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('resultado', models.TextField(blank=True, null=True, verbose_name='Resultado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('plano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='microcredito_app.plano')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_mpesa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação M-PESA',
                'verbose_name_plural': 'Transações M-PESA',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
