# Generated by Django 6.0.2 on 2026-04-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcredito_app', '0003_transacaompesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='notificacao_sms',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='notificacao_whatsapp',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='distrito',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Distrito'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/%Y/%m/', verbose_name='Foto/Logo'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone/WhatsApp'),
        ),
    ]
