# Generated by Django 6.0.2 on 2026-04-17 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcredito_app', '0005_provincia_distrito_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='microcredito_app.provincia', verbose_name='Província'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='microcredito_app.cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='microcredito_app.distrito', verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
    ]
