# Generated by Django 6.0.2 on 2026-04-17 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcredito_app', '0006_perfilusuario_provincia_alter_perfilusuario_cidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone/WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail de Contato')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/%Y/%m/', verbose_name='Logo da Empresa')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('suspensa', 'Suspensa'), ('cancelada', 'Cancelada')], default='ativa', max_length=20, verbose_name='Status')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token WhatsApp Business')),
                ('whatsapp_phone_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone ID WhatsApp')),
                ('sms_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='API Key SMS')),
                ('notificar_vencimento', models.BooleanField(default=True, verbose_name='Notificar vencimento')),
                ('notificar_atraso', models.BooleanField(default=True, verbose_name='Notificar atraso')),
                ('dias_antecedencia', models.IntegerField(default=5, verbose_name='Dias de antecedência')),
                ('atraso_frequencia', models.IntegerField(default=2, verbose_name='Frequência de alertas em atraso (dias)')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_notificacao', to='microcredito_app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vencimento', 'Lembrete de Vencimento'), ('atraso', 'Alerta de Atraso'), ('cobranca', 'Alerta para Credor')], max_length=20, verbose_name='Tipo')),
                ('destinatario', models.CharField(max_length=20, verbose_name='Destinatário (telefone)')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('falhou', 'Falhou')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_agendamento', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='microcredito_app.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='microcredito_app.empresa')),
                ('parcela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='microcredito_app.parcela')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_envio'],
            },
        ),
    ]
