# Generated by Django 6.0.2 on 2026-04-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcredito_app', '0009_fcmtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaonotificacao',
            options={'verbose_name': 'Configuração de Notificação', 'verbose_name_plural': 'Configurações de Notificações'},
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='push_alertar_atraso',
            field=models.BooleanField(default=True, verbose_name='Alertar sobre parcelas em atraso'),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='push_alertar_vencimento',
            field=models.BooleanField(default=True, verbose_name='Alertar sobre parcelas próximas'),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='push_dias_antecedencia',
            field=models.IntegerField(default=3, verbose_name='Dias de antecedência push'),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='push_horario_fim',
            field=models.TimeField(default='20:00', verbose_name='Horário fim'),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='push_horario_inicio',
            field=models.TimeField(default='08:00', verbose_name='Horário início'),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='push_notificacoes_ativas',
            field=models.BooleanField(default=True, verbose_name='Ativar notificações push'),
        ),
    ]
