# Generated by Django 6.0.2 on 2026-04-27 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcredito_app', '0010_alter_configuracaonotificacao_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('admin_empresa', 'Administrador da Empresa'), ('gerente', 'Gerente'), ('caixa', 'Caixa'), ('atendente', 'Atendente')], default='atendente', max_length=20, verbose_name='Cargo')),
                ('pode_baixar_emprestimos', models.BooleanField(default=False, verbose_name='Pode baixar empréstimos')),
                ('pode_regularizar_parcelas', models.BooleanField(default=False, verbose_name='Pode regularizar parcelas')),
                ('pode_configurar_empresa', models.BooleanField(default=False, verbose_name='Pode configurar empresa')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='microcredito_app.empresa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
