# Generated by Django 6.0.2 on 2026-05-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcredito_app', '0012_emailverificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentoassinatura',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('emola', 'E-MOLA'), ('mpesa', 'M-PESA'), ('transferencia', 'Transferência'), ('cartao', 'Cartão')], max_length=20, verbose_name='Forma de Pagamento'),
        ),
    ]
