# Generated by Django 5.1.6 on 2026-08-27 09:58

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcredito_app', '0013_alter_pagamentoassinatura_forma_pagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bi_passaporte',
            field=models.CharField(blank=True, db_index=True, help_text='BI (Letra+6 dígitos), Passaporte (Letra+7 dígitos) ou DIRE (8 dígitos)', max_length=20, null=True, verbose_name='BI/Passaporte'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_emissao_documento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão do Documento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_validade_documento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade do Documento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nuib',
            field=models.CharField(blank=True, db_index=True, help_text='Número Único de Identificação do Bilhete (9 dígitos)', max_length=9, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{9}$', 'NUIB deve ter exatamente 9 dígitos numéricos.')], verbose_name='NUIB'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nuit',
            field=models.CharField(blank=True, db_index=True, help_text='Número Único de Identificação Tributária (9 dígitos)', max_length=9, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{9}$', 'NUIT deve ter exatamente 9 dígitos numéricos.')], verbose_name='NUIT'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nuit'], name='microcredit_nuit_07640e_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nuib'], name='microcredit_nuib_af35b2_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['bi_passaporte'], name='microcredit_bi_pass_69c50e_idx'),
        ),
    ]
