# Generated by Django 5.1.6 on 2026-08-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcredito_app', '0014_cliente_bi_passaporte_cliente_data_emissao_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='bi_passaporte',
            field=models.CharField(blank=True, db_index=True, help_text='BI: 1234567890123A (13 dígitos + letra com Módulo 23) | Passaporte: MZ1234567 | DIRE: 1234567890123X (13 dígitos + letra)', max_length=14, null=True, verbose_name='BI/Passaporte'),
        ),
    ]
